[platformio]
default_envs = enrollment

[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps =
    miguelbalboa/MFRC522@^1.4.11
    bblanchon/ArduinoJson@^6.21.5
    marcoschwartz/LiquidCrystal_I2C@^1.1.4
build_flags =
    -DAPP_BASE_URL=\"https://slsubcpatrol.site\"
    -DRFID_SS_PIN=5
    -DRFID_RST_PIN=27
    -DLCD_SDA_PIN=21
    -DLCD_SCL_PIN=22
    -DLCD_COLUMNS=16
    -DLCD_ROWS=2
    -DBUZZER_PIN=26
    -DWIFI_CONNECT_ATTEMPTS=40

[env:enrollment]
extends = env
build_flags =
    ${env.build_flags}
    -DDEVICE_MODE=1
    -DDEVICE_UID=\"ESP32-REG-01\"
    -DDEVICE_LABEL=\"Enrollment_Reader\"
    -DAPI_PATH=\"/api/rfid-enrollment\"
    -DBUZZER_ACTIVE_HIGH=1
    -DSCAN_COOLDOWN_MS=2500
    -DHTTP_TIMEOUT_MS=15000

[env:checkpoint_gh]
extends = env
build_flags =
    ${env.build_flags}
    -DDEVICE_MODE=2
    -DDEVICE_UID=\"ESP32-GH-01\"
    -DDEVICE_LABEL=\"Guard_House\"
    -DAPI_PATH=\"/api/rfid-scan\"
    -DBUZZER_ACTIVE_HIGH=0
    -DSCAN_COOLDOWN_MS=3000
    -DHTTP_TIMEOUT_MS=65000

[env:checkpoint_it]
extends = env
build_flags =
    ${env.build_flags}
    -DDEVICE_MODE=2
    -DDEVICE_UID=\"ESP32-IT-01\"
    -DDEVICE_LABEL=\"IT_Building\"
    -DAPI_PATH=\"/api/rfid-scan\"
    -DBUZZER_ACTIVE_HIGH=1
    -DSCAN_COOLDOWN_MS=3000
    -DHTTP_TIMEOUT_MS=65000

[env:checkpoint_mpc]
extends = env
build_flags =
    ${env.build_flags}
    -DDEVICE_MODE=2
    -DDEVICE_UID=\"ESP32-MPC-01\"
    -DDEVICE_LABEL=\"MPC_Checkpoint\"
    -DAPI_PATH=\"/api/rfid-scan\"
    -DBUZZER_ACTIVE_HIGH=1
    -DSCAN_COOLDOWN_MS=3000
    -DHTTP_TIMEOUT_MS=65000

[env:checkpoint_fi]
extends = env
build_flags =
    ${env.build_flags}
    -DDEVICE_MODE=2
    -DDEVICE_UID=\"ESP32-FI-01\"
    -DDEVICE_LABEL=\"FI_Checkpoint\"
    -DAPI_PATH=\"/api/rfid-scan\"
    -DBUZZER_ACTIVE_HIGH=1
    -DSCAN_COOLDOWN_MS=3000
    -DHTTP_TIMEOUT_MS=65000

[env:checkpoint_canteen]
extends = env
build_flags =
    ${env.build_flags}
    -DDEVICE_MODE=2
    -DDEVICE_UID=\"ESP32-CAN-01\"
    -DDEVICE_LABEL=\"Canteen_Checkpoint\"
    -DAPI_PATH=\"/api/rfid-scan\"
    -DBUZZER_ACTIVE_HIGH=1
    -DSCAN_COOLDOWN_MS=3000
    -DHTTP_TIMEOUT_MS=65000

[env:checkpoint_ag]
extends = env
build_flags =
    ${env.build_flags}
    -DDEVICE_MODE=2
    -DDEVICE_UID=\"ESP32-AG-01\"
    -DDEVICE_LABEL=\"AG_Checkpoint\"
    -DAPI_PATH=\"/api/rfid-scan\"
    -DBUZZER_ACTIVE_HIGH=1
    -DSCAN_COOLDOWN_MS=3000
    -DHTTP_TIMEOUT_MS=65000
